name: CI
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    env:
      POSTGRES_USER: postgres
      PGPASSWORD: postgres
    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
            python-version: '3.6'
            django-version: '3.2.13'
          - os: ubuntu-20.04
            python-version: '3.7'
            django-version: '3.2.13'
          - os: ubuntu-20.04
            python-version: '3.8'
            django-version: '3.2.13'
          - os: ubuntu-20.04
            python-version: '3.9'
            django-version: '3.2.13'
          - os: ubuntu-20.04
            python-version: '3.10'
            django-version: '3.2.13'
          - os: ubuntu-20.04
            python-version: 'pypy3'
            django-version: '3.2.13'
          - os: ubuntu-20.04
            python-version: '3.9'
            django-version: '4.0.4'
          - os: ubuntu-20.04
            python-version: '3.10'
            django-version: '4.0.4'
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: 'Set up Python ${{ matrix.python-version }}'
        uses: actions/setup-python@v2
        with:
          python-version: '${{ matrix.python-version }}'
      - uses: actions/checkout@v2
      - run: pip install django==${{ matrix.django-version}}
      - run: pip install psycopg2
      - run: pip install gevent
      - run: python setup.py -q install
      - run: python runtests.py
